# GoldenDupes Dupe Plugin #
#    by Ivan Volkov
#    @Ivan8or#7412 on discord

#  1.12.2 autocraft dupe
autocraft-dupe:

# is this dupe enabled?
  enabled: true

#  does the dupe try to be as vanilla as possible (overrides a lot of config settings)
  vanilla: false

#  does the dupe give more items the more times the autocraft was clicked?
#     false =  the dupe gives the max number of items regardless of number of clicks
#     true  =  the dupe gives (number of clicks) * (multiplier) items
  items-by-click: true

#  only relevant if the items-per-click is set to true
  multiplier: 2

# the largest amount of items this dupe can give (capped at 64)
  max-items: 64


#  1.15 autocraft dupe
donkey-dupe:

  # is this dupe enabled?
  enabled: true

  # do donkeys in boats get duped when a player dc's riding the boat / donkey?
  do-boats: true


########################
# GLOBAL ITEM SETTINGS #
########################

# any non-64 stacked item (buckets, armor, tools, et.)
non-stackables:
# can they be duped?
  dupe: true
# what is the max duped stack size?
  stack-to: 64

# shulker boxes of any color
shulkers:
# can they be duped?
  dupe: true
# what is the max duped stack size?
  stack-to: 1

# totems pf undying
totems:
# can they be duped?
  dupe: true
# what is the max duped stack size?
  stack-to: 4







